package com.xiangzi.sapanywhere.info;

public class AddressInfo extends BaseInfo {

	// string,Country code.
	// Please refer to ISO 3166-1 alpha-2 as the country code abbreviation
	// standard.
	// 国家/地区
	private String countryCode;
	// State code.
	// Please notice that only state code in US, CN and GB are supported
	// currently.
	// 省（直辖市）
	private String stateCode;
	// State description.
	// Please provide the state information here if the state is not in US, CN
	// and GB and leave the state code field as null.
	// 省（直辖市）名称
	private String state;
	// City name.
	// 城市
	private String cityName;
	// Main street description.
	// 街道地址一,街道名、门牌号或邮政信箱
	private String street1;
	// Concrete location description.
	// 街道地址二,楼号（公寓号，单元号）、楼层和房间号
	private String street2;
	// Zip code. 邮政编码
	private String zipCode;
	// Mobile.
	// 手机
	private String mobile;
	// Telephone.
	// 座机
	private String telephone;
	// Recipient name. 收件人姓名
	private String recipientName;
	// Display name generated by address information from other address fields.
	// 显示名称
	private String displayName;
	// Address type. // It is an optional field, which is free style
	// 类型
	private String addressType;

	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getStateCode() {
		return stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getStreet1() {
		return street1;
	}

	public void setStreet1(String street1) {
		this.street1 = street1;
	}

	public String getStreet2() {
		return street2;
	}

	public void setStreet2(String street2) {
		this.street2 = street2;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getRecipientName() {
		return recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getAddressType() {
		return addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}
	
}
